server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: ubuntu
    username: admin
    password: admin
    host: 192.168.73.21

leyou:
  sms:
    accessKeyId: LTAIc259TULYzaS7
    accessKeySecret: 1uh79I1UAmwQ4YWsSmOgxw7JEBGA0v
    signName: 铭钧凯商城
    verifyCodeTemplate: SMS_148614415
